/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as ApiPostsIdRouteImport } from './routes/api/posts/$id'
import { Route as ApiMediaFilenameRouteImport } from './routes/api/media/$filename'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPostsIdRouteImport } from './routes/admin/posts/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/admin/posts/',
  path: '/admin/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIdRoute = ApiPostsIdRouteImport.update({
  id: '/api/posts/$id',
  path: '/api/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaFilenameRoute = ApiMediaFilenameRouteImport.update({
  id: '/api/media/$filename',
  path: '/api/media/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/admin/posts/$id',
  path: '/admin/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$filename': typeof ApiMediaFilenameRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/api/posts': typeof ApiPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$filename': typeof ApiMediaFilenameRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/api/posts': typeof ApiPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$filename': typeof ApiMediaFilenameRoute
  '/api/posts/$id': typeof ApiPostsIdRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/posts/$slug'
    | '/posts'
    | '/admin/posts/$id'
    | '/api/auth/$'
    | '/api/media/$filename'
    | '/api/posts/$id'
    | '/admin/posts'
    | '/api/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/posts/$slug'
    | '/posts'
    | '/admin/posts/$id'
    | '/api/auth/$'
    | '/api/media/$filename'
    | '/api/posts/$id'
    | '/admin/posts'
    | '/api/posts'
  id:
    | '__root__'
    | '/'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/posts/$slug'
    | '/posts/'
    | '/admin/posts/$id'
    | '/api/auth/$'
    | '/api/media/$filename'
    | '/api/posts/$id'
    | '/admin/posts/'
    | '/api/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaFilenameRoute: typeof ApiMediaFilenameRoute
  ApiPostsIdRoute: typeof ApiPostsIdRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/$id': {
      id: '/api/posts/$id'
      path: '/api/posts/$id'
      fullPath: '/api/posts/$id'
      preLoaderRoute: typeof ApiPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$filename': {
      id: '/api/media/$filename'
      path: '/api/media/$filename'
      fullPath: '/api/media/$filename'
      preLoaderRoute: typeof ApiMediaFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/admin/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaFilenameRoute: ApiMediaFilenameRoute,
  ApiPostsIdRoute: ApiPostsIdRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
